# meta-opentools layer configuration

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "opentools"
BBFILE_PATTERN_opentools = "^${LAYERDIR}/"
BBFILE_PRIORITY_opentools = "10"

LAYERDEPENDS_opentools = "core raspberrypi qt6-layer"
LAYERSERIES_COMPAT_opentools = "scarthgap"

# Custom partition layout (read-only rootfs + writable /data) lives here.
WKS_SEARCH_PATH .= ":${LAYERDIR}/wic"
